apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-vs
spec:
  hosts:
    - app.dev.localhost
  gateways:
    - istio-system/ops-gateway
  http:
    # 1. IAM Service
    - name: ps-iam-route
      match:
        - uri:
            prefix: /api/v1/auth
        - uri:
            prefix: /api/v1/users
      route:
        - destination:
            host: iam.apps.svc.cluster.local
            port:
              number: 3000

    # Vault Service
    - name: ps-vault-route
      match:
        - uri:
            prefix: /api/v1/vault/
      rewrite:
        uri: /
      route:
        - destination:
            host: vault.apps.svc.cluster.local
            port:
              number: 3000

    # Audit Service
    - name: ps-audit-route
      match:
        - uri:
            prefix: /api/v1/audit/
      rewrite:
        uri: /
      route:
        - destination:
            host: audit.apps.svc.cluster.local
            port:
              number: 3000

    # Policy Service
    - name: ps-policy-route
      match:
        - uri:
            exact: /api/v1/password-policy/current
        - uri:
            exact: /api/v1/password/policy/
      route:
        - destination:
            host: policy.apps.svc.cluster.local
            port:
              number: 3000

    - name: frontend
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Chart.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
