apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ops-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range $app, $domain := .Values.domains }}
      - "{{ $domain }}"
    {{- end }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    {{- range $app, $domain := .Values.domains }}
      - "{{ $domain }}"
    {{- end }}
    tls:
      mode: SIMPLE
      credentialName: ingress-wildcard-cert
