apiVersion: v1
kind: Secret
metadata:
  name: nats-user-creds
type: Opaque
stringData:
  {{- range $username, $password := .Values.natsAuth.users }}
  {{ printf "NATS_USER_%s_PASSWORD" (upper $username | replace "-" "_") }}: {{ $password | quote }}
  {{- end }}
