domains:
  keycloak: "keycloak.dev.localhost"

kcSecrets:
  KEYCLOAK_ADMIN_PASSWORD: admin

kcConfig:
  KEYCLOAK_ADMIN: admin
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HOSTNAME: "{{ .Values.domains.keycloak }}"
  KC_PROXY_HEADERS: "xforwarded"
  KC_HTTP_ENABLED: "true"

keycloakx:
  fullnameOverride: "keycloak"
  replicas: 1

  image:
    tag: "26.6.3"

  command:
  - "/opt/keycloak/bin/kc.sh"
  args:
  - "start"
    
  dbchecker:
    enabled: true

  database:
    vendor: postgres
    hostname: postgres-rw.database.svc.cluster.local
    port: 5432
    username: keycloak-admin
    password: admin
    database: keycloak

  proxy:
    enabled: false

  health:
    enabled: true
  
  metrics:
    enabled: true

  http:
    relativePath: "/"

  livenessProbe: |
    httpGet:
      path: /health/live
      port: 9000
    initialDelaySeconds: 0
    timeoutSeconds: 5

  readinessProbe: |
    httpGet:
      path: /health/ready
      port: 9000
    initialDelaySeconds: 10
    timeoutSeconds: 1

  startupProbe: |
    httpGet:
      path: /health
      port: 9000
    initialDelaySeconds: 15
    timeoutSeconds: 1
    failureThreshold: 60
    periodSeconds: 5

  extraEnvFrom: |
    - configMapRef:
        name: keycloak-config
    - secretRef:
        name: keycloak-secrets
  
  extraEnv: |
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless