dbUser: ENC[AES256_GCM,data:SXfnC43s3ES6h+TNAg==,iv:E/1up8CNdbXV+vKUiTZqXgqWfZLHVtTkfPXDkN17nNs=,tag:PsV22wLfnv0LeVMkd2qI0Q==,type:str]
dbPassword: ENC[AES256_GCM,data:1DVD+hw=,iv:EUVA5kc9N2HSrVEL4rTNomwZ9geHWyyaJLTaJcJo4Y4=,tag:HC+fcD4kyZNOC6z58Ra6Zw==,type:str]
configServerAccessToken: ENC[AES256_GCM,data:RbW1FH8LVnGR271p7jVUoViNHl8Esv68,iv:v7uoBgFU/jiKVZ9/0e7Urh9QPN3+n4jzB5IzKVHrmtQ=,tag:GdC/tIz44WIwi40QMZLTkw==,type:str]
natsPassword: ENC[AES256_GCM,data:TiZACVyZBLTS7OOrbX4P,iv:3DAhKl6rUG7XJ0muoW5rxkFTehvam/PwevX74HV+4Q0=,tag:1afC+xg3ABCOiO2bwgjWkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTTBaWlBaNmJOQm1LellF
            K3ZBNjh6TzAvVEh5Tmg1M3pNUS9JeVJIdFY4CnZqelRWSjR2K09wdWljNW91dGZT
            dThrdkVkRDVuRldkd2dremZVVXFPaFUKLS0tIDF1TlFaNTA3T1kwTW1iRjllUXRa
            MmxWWjNtRkplNmRXeURVN1R6VElVeEEKi7Iusp8pAGfryu+I+t/M+MaJcSqyFzKo
            sCTBoX9/iVxOyPxL+IDJa5zlRK/OcU0QjBiJ/XrEJvc9/7c3o+/Rgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dx0uxanssvu2rnkrh2zs0ra6cddc40hga0qgeqkv5wf942paneds5xkj4l
    lastmodified: "2026-06-19T14:52:52Z"
    mac: ENC[AES256_GCM,data:rfT5Aegtlg+27JgcF08F2Ln4q76lTgwQ2kryFDHSPDlRti1qvf0+p8wQDF9Yqj+4awMIS4IRFAcmEY2E4B0gjjfP4ZtVaV5tvddb0vdd8LCv1mTfeFgZrW/qrTB9luaCEcR7xoL/bq1S0eKGj/mi5WtHCw+beRedMLOxqk03c70=,iv:LLI5w82NmGYargehAzdhcqd98Z0gLUgGuxT6TlQdfY4=,tag:XAdEL0ke9Y9w5ur60yx6IA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
