apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: database
type: Opaque
stringData:
  ACCESS_KEY_ID: "rustfsadmin"
  ACCESS_SECRET_KEY: "rustfsadminpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-creds
type: Opaque
stringData:
  username: postgres
  password: {{ .Values.postgresPassword | quote }}
---
{{- range .Values.customRoles }}
{{- if .password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-creds
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .name }}
  password: {{ .password | quote }}
---
{{- end }}
{{- end }}
