apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vc
spec:
  hosts:
    - "{{ .Values.domains.grafana }}"
  gateways:
    - istio-system/ops-gateway
  http:
    - route:
        - destination:
            host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
            port:
              number: 80
