domains:
  grafana: "default.local"

kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: "admin"
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false

      retention: 10d

      resources:
        requests:
          memory: 400Mi
