configToken: ENC[AES256_GCM,data:Ji4Y+4ROIK5uZm9DrjEPnA==,iv:h7wUA8ifaKHvW4ioc1PEQRp6LoLoLzLPy6CzGMpvQeI=,tag:noc4mXkilg14oXAf/8mp0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M3BVOXhZaEJ6L2YvVTQ2
            Vk1vdWRyVFg2b0N5NEZsVUdDOVREQ2RUZjFvCmY0Tm1VNnluYkVJSXF1ek00SlpB
            RjNMMzlnZFRMalZzY0wySjV1blV4Q28KLS0tIEpaQ1lZdDVFb1FQY2wwdTF0bUdJ
            bERBa2Z1cm9YQXMyd3JMSkUrT0NDYVEK1f+So4106Yf8ix8smVWaMa1c5YDm4kQ7
            nvyJ5NNKjsWlb+mH32ijXq4rPodOwSnnn3YX52yYbOuEY279nQcJ6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dx0uxanssvu2rnkrh2zs0ra6cddc40hga0qgeqkv5wf942paneds5xkj4l
    lastmodified: "2026-06-19T14:56:25Z"
    mac: ENC[AES256_GCM,data:FbA6MjOCrS5S5sFbU6AK/is/xx/DgpVWOL8dVgnQA2MmJJqZa4XbcaEwAX/te5ZzeX4OXayFhSuji+MQKgAyXmbZ54Br5C5g39onAGhQwIHXC9TyNtis1LSQH5iKBpJbOJQVb1N7cs53FPvF4VgvXbciJzExg1MFM+Evyl6WqPc=,iv:J13jllezgBRYbP+oW0hTbqHOe6Khnn2I31oQnTqxo80=,tag:YxVUYkdq50g9hMIliSk1wA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
