configToken: ENC[AES256_GCM,data:d5JKQwsawqv8I7WYfTfaDQ==,iv:d6k/TT+XY+ZJ3LVTxGPojgj2yGzKOqFX4I6alSYJ0dk=,tag:kct8LW1jmqmInYuBeIwTeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSVJMWWt4U1B4RjJzdnky
            dSswU3QyZm9hN2NCcExNTWZGckpOMW5RNEdJClVSTGZDS3ZKUHFoL2hLbnBBTG1N
            MzVLRWFiRmdzaUQyc3ZYbFgyZ2sxNHMKLS0tIHdyWlgxc0JxMnA2OGRaNzlyUUxz
            TGttSGZRaGFZY2RQQ3VTZVVjRDlFVjAK/JYaXfg/SfBRcjXESQ7hhFnl17D3fB4j
            9NrmzjVzKzZoFbQCTPw7/AgCLM+QCwF4EFRJfH4spBsZpEmZmzhCLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dx0uxanssvu2rnkrh2zs0ra6cddc40hga0qgeqkv5wf942paneds5xkj4l
    lastmodified: "2026-06-17T16:16:50Z"
    mac: ENC[AES256_GCM,data:cIObE0X1/InDZ9pvN6hJmeIAZwJmQYVLMosU/46twi104ndVcLD9Qabi9CESPDU1FDh11zvXvYEMOB7EN3dsYzddH8MO6/CTfnhPyWk8iiQcFZj6540lzJM+ntFlrEV0SODM0IpUj/YHsKFWfC0QBD7ArY9Y2ayZqRgDRcy8HX0=,iv:WqtmA/lnwIPxvngE4kUeZn39MlgUvnN1oyYE4v/4l4E=,tag:rLb7wVjABZ/MmD/cfaBlqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
