replicaCount: 1

image:
  repository: local-registry:5000/config-server
  pullPolicy: Always
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

autoscaling:
  enabled: false

podSecurityContext: {} # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

domains:
  configServer: "default.local"

service:
  type: ClusterIP
  port: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env:
  - name: SPRING_APPLICATION_NAME
    value: "config-server"
  - name: CONFIG_GIT_URI
    value: "https://github.com/pass-shield/ps-config.git"
  - name: XDG_CONFIG_HOME
    value: /tmp/.config
  - name: CONFIG_TOKEN
    valueFrom:
      secretKeyRef:
        name: config-server-secret
        key: config-token
  - name: CONFIG_GIT_BRANCH
    value: "main"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: management
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: management

volumes:
  - name: tmp-volume
    emptyDir: {}

volumeMounts:
  - name: tmp-volume
    mountPath: /tmp

nodeSelector: {}

tolerations: []

affinity: {}
