replicaCount: 1

image:
  repository: registry.local/config-server
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {} # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

domains:
  configServer: "default.local"

service:
  type: ClusterIP
  port: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8888
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8888

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
