apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-routing
spec:
  hosts:
    - kiali.localhost
  gateways:
    - kiali-gateway
  http:
    - route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001
