instances: 1
storageSize: 1Gi

postgresPassword: admin

customRoles:
  - name: &kc-admin keycloak-admin
    password: "admin"
    login: true
    comment: "Keycloak admin role"
  - name: &auditor-admin auditor-admin
    password: "admin"
    login: true
    comment: "Auditor admin role"
  - name: &advisor-admin advisor-admin
    password: "admin"
    login: true
    comment: "Advisor admin role"

customDatabases:
  - name: keycloak
    owner: *kc-admin
  - name: audit-logs
    owner: *auditor-admin
  - name: advisor
    owner: *advisor-admin
