apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: rustfs-vs
spec:
  hosts:
    - "{{ .Values.domains.rustfs }}"
  gateways:
    - istio-system/ops-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: rustfs-svc.storage.svc.cluster.local
            port:
              number: 9001
