apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-dynamic-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: {{ .Values.repoURL }}
      revision: {{ .Values.targetRevision }}
      files:
      - path: "gitops/charts/apps/**/.argocd.yaml"
  template:
    metadata:
      name: '{{ "{{ .path.basename }}" }}'
    spec:
      project: infrastructure
      source:
        repoURL: {{ $.Values.repoURL }}
        targetRevision: {{ $.Values.targetRevision }}
        path: '{{ "{{ .path.path }}" }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - values.yaml
          - secrets://secrets.enc.yaml
          - "../../../globals.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{ default \"default\" .targetNamespace }}" }}'
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
