apiVersion: v1
kind: Secret
metadata:
  name: ingress-wildcard-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ required "tls.cert value is missing in secrets.enc.yaml" .Values.tls.cert | b64enc | quote }}
  tls.key: {{ required "tls.key value is missing in secrets.enc.yaml" .Values.tls.key | b64enc | quote }}
