apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  db-user: {{ .Values.dbUser | quote }}
  db-password: {{ .Values.dbPassword | quote }}
  config-token: {{ .Values.configServerAccessToken | quote }}
  llm-api-key: {{ .Values.llmApiKey | quote }}
