dbUser: ENC[AES256_GCM,data:nG5GCcX83XWH,iv:c7a9XZzty7kzo5kZNpJeVRulc+kywGHpnrwrIRvj3YI=,tag:/K3ry/SXyEsqWIzpMZPQZQ==,type:str]
dbPassword: ENC[AES256_GCM,data:CQsPxuE=,iv:DrM+36hpIhCHk+7gGXNNDcrpIWx0S/SkBNIyA4TV6q0=,tag:i2OPfLxY5M6LTpZrhVWyyg==,type:str]
configServerAccessToken: ENC[AES256_GCM,data:zKEZVx3l4rvvZ/aEVroGpQ==,iv:8MCsUbdGUhPFO4n9uXu4RkJoe1E09t6Pbo/jKqIESxI=,tag:Gl0pVThzPpJm1dhZo18Rhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicVo5WURrMXo1ZWJTd09t
            SHRpVjF6TXJ3a0N5SFRscE9rcFp3d0tHYzI0CnQyaXVkTUVzRjZMeGNaVkE2OXJo
            NHdTL0g0NTZNejBaeG5NNWRUcDA0eGsKLS0tIHl4bVB3ZkFQbTNPNE5MRC9wRWw5
            dVg4cG1oSmxVRkdRT2d2NHJsOEJiUG8KiU8ylYkUMZMX3vkhvXvAd3/Vv/qciqFZ
            Cw4uYGrIAw08rsYvatDV7XhYDg+ButyBe3gCtb8O638QOWP6Vd7MBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dx0uxanssvu2rnkrh2zs0ra6cddc40hga0qgeqkv5wf942paneds5xkj4l
    lastmodified: "2026-06-20T14:51:43Z"
    mac: ENC[AES256_GCM,data:grx0eOeyF+RS8S210GPgDhJT2iSQPFSLfDq6XoCW4C9FrNw9NMP2lqiOTKkgRZbgmTj4ru0Rb/2r0DPaRNS96EpR85hGdtCGYGk8YNa9twd4lirFrAPbm1ogSdC+jN3kJCS+yHIxokF8ZGZcUeyyxWKKCm49dObvvg4AwDb4ego=,iv:gdwt8bdtJ0W6FppnsUGqDW93oOYEspwC3/BZYW3cgro=,tag:5FMqz/gPhEPjIcLmJbMMVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
