apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  host: argocd-server.argocd.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
      insecureSkipVerify: true
