apiVersion: v1
kind: Secret
metadata:
  name: ingress-wildcard-cert
  namespace: istio-system
  labels:
    app.kubernetes.io/name: argocd-expose
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/tls
data:
  tls.crt: {{ required "tls.cert value is missing in secrets.enc.yaml" .Values.tls.cert | b64enc | quote }}
  tls.key: {{ required "tls.key value is missing in secrets.enc.yaml" .Values.tls.key | b64enc | quote }}
