dbUser: ENC[AES256_GCM,data:Gcn7wGRwkcYxLzI=,iv:whmPxBaJnQqiSLi4V3cQbA7DRubPP3E+J31VH1D/u9s=,tag:tK2xBRj9SU0eUp2K1SEmGA==,type:str]
dbPassword: ENC[AES256_GCM,data:h5BO2uY=,iv:WL7HuH4YiqxvQassp4i7XIVN0WUDiQRgvJUV3IXp7ic=,tag:G5arykGgnCS1wpW7a9XeTQ==,type:str]
configServerAccessToken: ENC[AES256_GCM,data:V+NQvTPjUyYc6W+BbNgaiA==,iv:9HfwJakd9OjxKuKnKkGPwkUnKvrd4X/wYX3YaMk3eZ4=,tag:pGQ2m8cZ3LtnQaDZWuky6Q==,type:str]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbFdLZVFxUDFFQndnV1VI
              SVY5U0Y3VkgvMkFHZ1U1dzRyVlBJNWpiZWd3CmZPeElyNFJzYUd6VGw1YjF5YTFx
              MHNSbkZQelRJekkwcWhjZVVtcmRWdFUKLS0tIFNscjR4cnU0MVE2Q3pDYlh3TzVr
              cUx4MzNxbjNsT3V0cklEN1p0MkJjUjQK5vEkeDjpBx2c0B5tPNIszuQQLDST6vNJ
              PWHp4DMwBDGN0r8MmbAV8sWZb2/UGQCoL38u58BlQ9h3IvPi90Y7CA==
              -----END AGE ENCRYPTED FILE-----
          recipient: age1dx0uxanssvu2rnkrh2zs0ra6cddc40hga0qgeqkv5wf942paneds5xkj4l
    lastmodified: "2026-06-20T14:16:37Z"
    mac: ENC[AES256_GCM,data:vZd3LQQAFGVbmdKIO7SCF+x7ZbUu6LC0qBJJibzQZITl9e3bd5J6eSlOCRfEpcqd6DPusNBXCBPaq+wc5jNSnFNb+vKdkmtE45eTolDa3ZWJQsLpyz2yCKfW6vQfHcHOx+SAgSU3s7qDJyYsi5BCOjHivVd1WB2425haf90EWPE=,iv:0+rAf8i0Hs3zC3jiqtDmNF7BQ2CdrTfZNH1dY8D4sCY=,tag:cY+19w1hMLCeDxDcJgmLdg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
