dbUser: ENC[AES256_GCM,data:BfET87uSGUkGyI6ENQ==,iv:eekBDLbf6ZO63SD3i8WgJzy36+GZPhwy1qaC5k8F+5o=,tag:C0zswB2P8hQP+R/DswLbxA==,type:str]
dbPassword: ENC[AES256_GCM,data:ZJn461I=,iv:EmPxwuPFLig/4vUYvWmbOuAnQmbo6vAO3BhLrD7cObk=,tag:tBSxKAfGelVGH4s2imSf7Q==,type:str]
configServerAccessToken: ENC[AES256_GCM,data:wsm6fggzVu8qXl7BbJvnJw==,iv:vNKDz7DdrwhD+zHLDR/UnnQ/Bv0ir/+oIAibn7UvnWc=,tag:IMuPmAYTgKgAVo5Zg8BoQg==,type:str]
llmApiKey: ENC[AES256_GCM,data:FB534nPpZcflCE9wOVtekgLRrDFJNpO1vpdlWJyUub0I6sgbRgJr8noLQhUUR+NNa4nlGv8PffYzHNKqDHOvJu+J8h3/p28cHg==,iv:YbNK+PptD+7xoA4qjpUz8V1bTMsoAThvN7mwDo+ghHg=,tag:T1DpPlwSbeJWTaDvjuXvXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVWdXa3EyK0FGNFRKLzVM
            citDWXkrRE9aL05Lb1ZJdEYzcG85aFF6RzM0CjdQV1VzRmVSYm9abzIzN3pXVmdI
            Z0JyQzB5eHc3K29pWDZOTEljZjJQN00KLS0tIDJieWdPQlc5WWF5UHk0a3hNdnBJ
            WW9wdjB3UWRwZE85RTE0a1BkY1JrNTgKqj5viX2ZfQXwqMmrD9f1gPyrIXnYPpyT
            S2B2h1Q5GCV3Vwj4C9WVmduFFJSsXyIDOH0+CymtB3yVkEJxGEQ4oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dx0uxanssvu2rnkrh2zs0ra6cddc40hga0qgeqkv5wf942paneds5xkj4l
    lastmodified: "2026-06-19T22:35:00Z"
    mac: ENC[AES256_GCM,data:+T8CuzKQmqAcaYvfVbnMzYPdUtYYzixGaJFNBTqOvSSMjN3z+yzfkXrJsEqqvM5BaPJwDzS/4nmbnVwI4r56IXP5ipmI+9wx8grx1VLIdzCdDHmjLR1wh+GFMk2wGyIeV8fNIVJWD1qlKcotZ0WziwErFTVFmV4HW3D757KwVMU=,iv:6CQPGOMuMhyZBQW+7kphCZpwEVPeADskf4mlfGAliT0=,tag:f5g6ZpRglkEQQa+7FiHImQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
